#make BOLDdistilled lib persist.

services:
  map:
    image: ghcr.io/cbg-innov/map:latest
    pull_policy: missing
    working_dir: /MAP
    volumes:
      - reflib:/MAP/REFS
      - ${MAP_DATA:-./data}:/data
    command: ["sleep", "infinity"]
volumes:
  reflib: