#make BOLDdistilled lib persist.

services:
  map:
    build:
      context: .
    image: ghcr.io/cbg-innov/map:latest
    working_dir: /MAP
    volumes:
      - reflib:/MAP/REFS
      - ${MAP_DATA:-./data}:/data
    command: ["sleep", "infinity"]
volumes:
  reflib: