#make BOLDdistilled lib persist.

services:
  map:
    image: map:latest
    working_dir: /MAP
    volumes:
      - reflib:/MAP/REFS
      - ${MAP_DATA:-./data}:/data
    command:
      - bash
      - -lc
      - "bash /MAP/SCRIPTS/MAP.sh --fastq /data/*.fastq.gz --params /data/parameters.xlsx --wd /data"
volumes:
  reflib: